---
title: "Panning 2 Implementation"
author: "Luisa M. Mimmi"
date: "Prepared: `r format(Sys.time(), '%B %e, %Y')`"
output:
  html_document: 
    keep_md: yes
  pdf_document: default
bibliography: ['Plan2Imp.bib']
biblio-style: "apalike"
link-citations: true
#se non citi niente nel testo devi mettere questo
nocite: | 
  @*
---

## KEY MESSAGES 

### Public WorksStatus
> La situazione in Italia oggi è la seguente: vi sono circa 630 opere infrastrutturali bloccate per un controvalore di 54,4 miliardi di euro e nel 43% dei casi, ciò si deve a ostacoli procedurali o amministrativi. L’Italia, infine, non riesce a usare tutti i fondi europei ad essa destinati (sul programma 2014/2020 ne ha impegnati solo il 54% e spesi il 27%). // ruolo PA, Invitalia, CDP, // semplificazione normativa etc  [@aspen_institute_aspen_2020-1]


### Normative issues

+ l’abrogazione tout court del _Codice degli appalti_ (che peraltro costituisce il recepimento di direttive europee) e  sua sostanziale riforma in chiave semplificatoria.

+ rivisto recentemente _Regolamento di esecuzione, attuazione e integrazione del Codice dei contratti pubblici_

+ _economia della fiducia_ meno controlli ex-ante e piu controlli ex-post 


### Acknowledgments

##### Data



##### Inspiring open source R projects
+ [Bill Perry: Two-way ANOVA in R](https://wlperry.github.io/2017stats/05_6_twowayanova.html)
+ [Sharan Naribole: Data Exploration on H-1B Visa dataset](https://github.com/sharan-naribole/H1B_visa_eda)
+ [Fabio Votta: article on refugees and great data viz](https://favstats.eu/post/exploring_us_refugee_data/)
+ [Paul Williamson: Custom `crosstab` function](http://rstudio-pubs-static.s3.amazonaws.com/6975_c4943349b6174f448104a5513fed59a9.html)


##### Reference
